const DB_NAME='mapaflex-db',STORE='maps';let db,currentMap={id:'default',title:'Meu primeiro mapa',nodes:[]},drag=null,deferredPrompt=null;
const $=s=>document.querySelector(s);const workspace=$('#workspace'),tpl=$('#nodeTemplate'),statusEl=$('#saveStatus');
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function loadMap(){return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get('default');r.onsuccess=()=>{if(r.result)currentMap=r.result;res()};r.onerror=()=>rej(r.error)})}
function saveMap(){statusEl.textContent='Salvando...';return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(currentMap);tx.oncomplete=()=>{statusEl.textContent='Salvo localmente.';res()};tx.onerror=()=>{statusEl.textContent='Erro ao salvar.';rej(tx.error)}})}
function esc(v=''){return String(v)}
function render(){workspace.innerHTML='';$('#mapTitle').value=currentMap.title;$('#workspaceTitle').textContent=currentMap.title;$('#nodeCount').textContent=`${currentMap.nodes.length} ${currentMap.nodes.length===1?'balão':'balões'}`;currentMap.nodes.forEach(node=>{const el=tpl.content.firstElementChild.cloneNode(true);el.dataset.id=node.id;el.style.left=`${node.x}px`;el.style.top=`${node.y}px`;el.querySelector('h3').textContent=node.title;el.querySelector('p').textContent=node.text;el.querySelector('.delete-node').onclick=async()=>{if(confirm('Excluir este balão?')){currentMap.nodes=currentMap.nodes.filter(n=>n.id!==node.id);render();await saveMap()}};el.querySelector('.edit-node').onclick=async()=>{const t=prompt('Título do balão:',node.title);if(t===null)return;const c=prompt('Conteúdo do balão:',node.text);if(c===null)return;node.title=t.trim()||'Sem título';node.text=c;render();await saveMap()};el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={id:node.id,dx:e.clientX-node.x,dy:e.clientY-node.y,el};el.setPointerCapture(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!drag||drag.id!==node.id)return;node.x=Math.max(10,e.clientX-drag.dx);node.y=Math.max(10,e.clientY-drag.dy);el.style.left=`${node.x}px`;el.style.top=`${node.y}px`});el.addEventListener('pointerup',async()=>{if(!drag||drag.id!==node.id)return;el.classList.remove('dragging');drag=null;await saveMap()});workspace.appendChild(el)})}
$('#addNodeBtn').onclick=async()=>{const title=$('#nodeTitle').value.trim(),text=$('#nodeText').value.trim();if(!title&&!text)return alert('Digite um título ou conteúdo para o balão.');const i=currentMap.nodes.length;currentMap.nodes.push({id:crypto.randomUUID(),title:title||'Novo conceito',text,x:40+(i%4)*290,y:40+Math.floor(i/4)*190});$('#nodeTitle').value='';$('#nodeText').value='';render();await saveMap()};
$('#mapTitle').addEventListener('input',async e=>{currentMap.title=e.target.value.trim()||'Mapa sem título';$('#workspaceTitle').textContent=currentMap.title;await saveMap()});
$('#newMapBtn').onclick=async()=>{if(!confirm('Criar um mapa novo? O mapa atual será substituído neste navegador.'))return;currentMap={id:'default',title:'Novo mapa',nodes:[]};render();await saveMap()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(currentMap,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${currentMap.title.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()||'mapaflex'}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj||!Array.isArray(obj.nodes))throw new Error();currentMap={id:'default',title:obj.title||'Mapa importado',nodes:obj.nodes.map((n,i)=>({id:n.id||crypto.randomUUID(),title:esc(n.title||'Sem título'),text:esc(n.text||''),x:Number.isFinite(n.x)?n.x:40+(i%4)*290,y:Number.isFinite(n.y)?n.y:40+Math.floor(i/4)*190}))};render();await saveMap()}catch{alert('Arquivo de mapa inválido.')}e.target.value=''});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};
(async()=>{try{await openDB();await loadMap();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')}catch(e){console.error(e);statusEl.textContent='Falha ao iniciar armazenamento local.'}})();
